// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearCommand(arg1, arg2) {
  return window['go']['gui']['App']['ClearCommand'](arg1, arg2);
}

export function GetActions() {
  return window['go']['gui']['App']['GetActions']();
}

export function GetMIDIDevices() {
  return window['go']['gui']['App']['GetMIDIDevices']();
}

export function ListenForInput() {
  return window['go']['gui']['App']['ListenForInput']();
}

export function LoadSettings() {
  return window['go']['gui']['App']['LoadSettings']();
}

export function SelectDevice(arg1) {
  return window['go']['gui']['App']['SelectDevice'](arg1);
}

export function SetCommand(arg1, arg2, arg3) {
  return window['go']['gui']['App']['SetCommand'](arg1, arg2, arg3);
}
